### ISSUE TITLE
Support for fasthttp

### ISSUE THREAD

**Issue by goriunov** [lxzan/gws#107]
Hey!  Thanks for the hard work on the lib!

I am wondering does this lib support https://github.com/valyala/fasthttp integration, if instead of using net/http we use fasthttp?

**Comment by lxzan** [comment]
I've written some glue code to support fiber, and theoretically fasthttp could be used in a similar way.

```go
package main

import (
	"bufio"
	fiber "github.com/gofiber/fiber/v2"
	"github.com/lxzan/gws"
	"log"
	"net"
	"net/http"
	"net/url"
)

func main() {
	upgrader := gws.NewUpgrader(&Handler{}, nil)

	app := fiber.New(fiber.Config{})

	app.Get("/connect", func(c *fiber.Ctx) error {
		r, err := getRequest(c)
		if err != nil {
			return err
		}
		c.Context().HijackSetNoResponse(true)
		c.Context().Hijack(func(conn net.Conn) {
			w := &responseWriter{
				conn: conn,
			}
			socket, err := upgrader.Upgrade(w, r)
			if err != nil {
				log.Printf(err.Error())
				return
			}
			socket.ReadLoop()
		})
		return nil
	})

	app.Listen(":3003")
}

func getRequest(c *fiber.Ctx) (*http.Request, error) {
	URL, err := url.Parse(string(c.Request().URI().FullURI()))
	if err != nil {
		return nil, err
	}

	var r = &http.Request{
		Method: c.Method(),
		Header: http.Header{},
		URL:    URL,
	}
	c.Request().Header.VisitAll(func(key, value []byte) {
		r.Header.Set(string(key), string(value))
	})
	return r, nil
}

type responseWriter struct {
	conn net.Conn
}

func (r *responseWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	return r.conn, nil, nil
}

func (r *responseWriter) Header() http.Header { return http.Header{} }

func (r *responseWriter) Write(bytes []byte) (int, error) { return 0, nil }

func (r *responseWriter) WriteHeader(statusCode int) { return }

type Handler struct {
	gws.BuiltinEventHandler
}

func (c *Handler) OnMessage(socket *gws.Conn, message *gws.Message) {
	defer message.Close()
	socket.WriteMessage(message.Opcode, message.Bytes())
}
```

**Comment by goriunov** [comment]
I will try to give it a try sometime later, not sure how tricky it would be as fasthttp is not directly net/http compatible.

i believe there are some libraries that have websocket built on top of the fasthttp (seen them in readme of the fasthttp) including port of gorilla websocket, but i do like/prefer this lib as the code is very clean an well structured, and it is nicer to go through etc…

**Comment by goriunov** [comment]
Was able to hook it up to fast API, seems to work correctly! A quick question, we are converting the fast API request to default http request by copying over the headers and other items. And wrapping in to the response writer the connection. In your opinion does it have any negative impact on performance ? (just curios, have not done any testing myself yet)

**Comment by lxzan** [comment]
The performance will be reduced a bit, you can test it.
