### ISSUE TITLE
Expose IsClosed method

### ISSUE THREAD

**Issue by goriunov** [lxzan/gws#110]
I have noticed that gws internally has a check function for isClosed, to check if this websocket connection has been closed. Can we expose this function outside. There are lots of things in which case connection could be closed and i want to have ability to check if the client connection has been closed outside before performing some action.

Example could be if we run async goroutine that send message in intervals, and we need to exit that go routine if connection is closed. We could do it two ways by passing custom channel and triggering the event on that channel that could kill goroutine, or could just call IsClosed method on the client 😁

**Comment by lxzan** [comment]
Exporting IsClosed can easily lead to adding duplicate checks.

You can save all connections to a map, the onclose event triggers a delete operation, and all existing connections in the map are considered active.

**Comment by lxzan** [comment]
You can also implement this method yourself based on OnClose and Conn.Session() if you need to.

**Comment by goriunov** [comment]
Yes this is one approach, however it becomes bit cumbersome, especially at the point where every connection could require a different logic to be executed async based on the configuration we receive from the client.  Instead of running a simple go enclosed code and let it exit at it is own desire we have to try and get alot of items to sync in between using some time of addition map synchronisation mechanisms. It might be faster and require a less/duplicated checks but definitely adds unecessary complexity which i would prefere to avoid (in cases where performance is not that critical)

**Comment by lxzan** [comment]
so easy

```go
func (c *Handler) OnClose(socket *gws.Conn, err error) {
	socket.Session().Store("closed", 1)
}

func (c *Handler) IsClosed(socket *gws.Conn) bool {
	_, ok := socket.Session().Load("closed")
	return ok
}
```
