### ISSUE TITLE
Latency optimisation

### ISSUE THREAD

**Issue by goriunov** [lxzan/gws#112]
A quick question, 

Is there any configurations or optimisations can be done where the number of websockets that can connect does not matter much,  but we want to minimise the single connection latency as much as possible irrelevant to the resource usage? As you are well familiar with protocol and might have some ideas on what could be tweaks to get the lowest latency even if resource usage might suffer, would love your opinion. Even if it is not exposed in gws by on itself, still curious to know your thoughts?

Thanks in advance !

**Comment by lxzan** [comment]
Try turning off compression, using protobuf instead of json, and adding monitoring observations.
