### ISSUE TITLE
Question: HTTP Server is reused

### ISSUE THREAD

**Issue by goriunov** [lxzan/gws#113]
A quick question around this point in readme:

* If HTTP Server is reused, it is recommended to enable goroutine, as blocking will prevent the context from being GC.

If i am using the same HTTP server for HTTP requests and websocket connection, ex:

/ws -> only websocket connections
/other-path

What are the side affects i can expect? Will the http request be affected by this issue where the context will not be GCed or am i missing something?

**Comment by lxzan** [comment]
Does not affect HTTP short links

**Comment by goriunov** [comment]
Sorry, not sure what you mean by "HTTP short links" ?

**Comment by lxzan** [comment]
> Sorry, not sure what you mean by "HTTP short links" ?

HTTP connections with relatively short life cycles

**Comment by goriunov** [comment]
I see thanks!
