### ISSUE TITLE
Issues trying to connect to IPv6 Servers

### ISSUE THREAD

**Issue by sksar** [lxzan/gws#115]
When I try to connect to an IPv6 server using such URL: `wss://[2500:6280:100:d0::1c2c:4001]:7000`, 
it gives the error `dial tcp: address 2500:6280:100:d0::1c2c:4001:7000: too many colons in address`.

For some reason it seems it adds the port to the last, something like `:7000` in the above example, making it part of the IPv6 address itself.
I have investigated a lot, and seems the issue is coming from within **gws** code.

**Comment by sksar** [comment]
https://github.com/lxzan/gws/blob/586e980cec513a3c985d83b2075ece54f4421f13/client.go#L52C1-L53C92

Seems like these two lines here are causing the issue, to get the square brackets removed completely, from the IPv6.

**Comment by lxzan** [comment]
Would you be interested in creating a PR?

**Comment by lxzan** [comment]
fixed, release next week
https://github.com/lxzan/gws/commit/aa65011a18efbaca243ae15de84068c2c9d7a4b8
