### ISSUE TITLE
应该把websocket 握手错误的具体信息暴露出来，而不是一个笼统的handshake error，否则都不知道原因在哪里！

### ISSUE THREAD

**Issue by mebest100** [lxzan/gws#118]
**修改之前：就报一个handshake error,根本不知道错在哪里，这种设计是很糟糕的！**

![image](https://github.com/user-attachments/assets/a367a13e-298f-4c94-80f1-2112aff75fcc)

**修改之后：很明显就知道了错误原因是403 forbidden**
![image](https://github.com/user-attachments/assets/c29e97d3-bb2b-4648-8010-fcd72a10ae0b)

**Comment by lxzan** [comment]
可以考虑，优化下错误提示

**Comment by Unicode01** [comment]
我查了两个小时全是handshake error,根本不知道去哪查,直到看到你的issue,这设计太夸张了
