### ISSUE TITLE
修复CDN应用场景中wss握手遇到的403 forbidden错误

### ISSUE THREAD

**Issue by mebest100** [lxzan/gws#119]
为什么用CDN，不用我多说了就是为了加速，而cloudflare原生支持websocket穿透，所以我采用wss。如果不是这个原因，其实用原生的tcp更方便。我用websocket最重要的原因是CDN可以透传wss请求转发给自己的VPS。
但是CDN域名直接解析的ip往往不理想，所以就出现了通过**CDN边缘IP/中转IP/优先IP加速**的方法，这个本质就是anycast任播技术。
一个典型的场景就是**wss://CDN-Edge-IP:443/${path}**

如果按照你这个gws的客户端典型配置来看：
```
conn, _, err := gws.NewClient(&gws.BuiltinEventHandler{}, &gws.ClientOption{
		Addr:          url,
		TlsConfig:     tlsConfig,
		RequestHeader: header,
	})
```
只要tlsconfig中配置了server_name（sni）和RequestHeader的Host字段也配置了SNI, 那么就应该不会出现403 forbidden错误。
因为这是CDN厂家出现403 forbidden错误最关键的原因。

但是实际测试中发现GWS的wss握手始终会出现403 forbidden错误：
![image](https://github.com/user-attachments/assets/7a3a77a1-3e41-4ebc-bd63-6ed494c46c22)

于是我开始走读代码，发现http.NewRequestWithContext的入参c.option.Addr, 实际会传递给Request的Host字段：
![image](https://github.com/user-attachments/assets/fe94e027-84b5-4d9b-8e8e-3bc739527f6d)

![image](https://github.com/user-attachments/assets/911dd6cd-e8dc-4851-85cc-1604e089ad9a)

但是注意了：c.option.Addr是**wss://CDN-Edge-IP:443/${path}**格式，那么解析出来的Host就是IP地址！而不是SNI域名。
这就有大问题了！
因为CDN这个时候会发现**tlsConfig中的ServerName居然和Request中的Host不一致**，一个是域名，一个是IP，所以这个时候就会抛出403 forbidden错误。

那么在处理http.NewRequestWithContext的入参c.option.Addr时必须把里面的ip替换成SNI域名：
**wss://CDN-Edge-IP:443/${path}  ==》**  ** wss://${SNI}:443/${path}  **

解决办法，修改gws源码client.go中的NewClient方法，增加以下代码：

```
// CDN场景Addr必须替换成SNI而不能是IP
		if option.TlsConfig.ServerName != "" && option.RequestHeader.Get("Host") != "" {
		 option.Addr = getNewAddr(option.Addr, option.TlsConfig.ServerName)
		}


// 把wss://${ip}:443/${path} 替换成把wss://${sni}:443/${path}
func getNewAddr(addr string,sni string) string  {
	// 定义正则表达式，匹配 :// 和 : 之间的内容
	re := regexp.MustCompile(`://([^:]+):`)
	// 替换匹配到的内容
	return re.ReplaceAllString(addr, "://"+sni+":")

}

```

![image](https://github.com/user-attachments/assets/0db2125b-4bc1-4a4c-a0c3-ba2f82b6428e)

最后问题解决：
![image](https://github.com/user-attachments/assets/6497e974-10d3-40e0-9576-7971abbf88af)

**Comment by lxzan** [comment]
有测试地址吗

**Comment by mebest100** [comment]
测试地址：wss://104.19.37.65:443/ws  ，这个里面的ip就是cloudflare的边缘优选ip
但是因为每个人的网络地区不一样,你不一定用的了。
你如果在浏览器访问104.19.37.65:443返回下面的页面，就说明可以用

![image](https://github.com/user-attachments/assets/1439129f-734c-4d19-bb5a-1c160734cd15)

如果用不了，就从下面的网站找一个。
https://cf.090227.xyz/

你理解错了，不是这样。是你那个源码中http.NewRequestWithContext中对于入参c.option.Addr处理的有问题，当用ip拨号时，就算ClientOption里面用域名（header里面host也要设置SNI），也会报403

你用下面的例子试一下就知道了：

```
sni := "testwebsocket.icanfly668.top"
header := http.Header{}
header.Set("Host", sni)
dialAddr :="wss://104.19.37.65:443/ws"

gws.NewClient(&WebSocketHandler{}, &gws.ClientOption{
		Addr: dialAddr,
		TlsConfig: &tls.Config{
			InsecureSkipVerify: true,
			ServerName:     sni,
		},
		RequestHeader: header,
	})

```
还有：你那个checkHeaders里面要把具体错误暴露出来，不然只能看到handshake error, 没法知道具体错误

**Comment by lxzan** [comment]
还是不行, 会报502

```
GET /ws HTTP/1.1
Host: testwebsocket.icanfly668.top
User-Agent: Go-http-client/1.1
Connection: Upgrade
Sec-Websocket-Key: srAhQDobi0n92v07+HVGqQ==
Sec-Websocket-Version: 13
Upgrade: websocket

```

**Comment by mebest100** [comment]
502就是对的，那说明wss握手已经成功。
因为我vps的websocket后端没有打开, 这个是cdn转发到我后端ngnix, 然后nginx在根据sni域名转发到websocket服务端。
我现在把vps的websocket后端打开了，你再试试，现在应该有消息返回了

**Comment by lxzan** [comment]
我的设想是正确的

```go
package main

import (
	"fmt"
	"log"
	"net"
	"strings"

	"github.com/lxzan/gws"
)

type MyDialer struct {}

func (c *MyDialer) Dial(network, addr string) (conn net.Conn, err error) {
	return net.Dial("tcp", "104.19.37.65:443")
}

func main() {
	socket, respHeaders, err := gws.NewClient(&WebSocket{}, &gws.ClientOption{
		Addr:      "wss://testwebsocket.icanfly668.top/ws",
		NewDialer: func() (gws.Dialer, error) { return new(MyDialer), nil },
	})
	if err != nil {
		log.Printf(err.Error(), &respHeaders)
		return
	}
	socket.ReadLoop()
}
```

recv: this is server reply!

**Comment by mebest100** [comment]
行吧，这样也可以也行。毕竟项目是你写的，我也不知道你是这样设计的。但你这个就有一个限制： ClientOption里面的Addr只能是域名不能是ip, 而且还需要手动构造一个NewDialer，感觉有点繁琐，不如wss://104.19.37.65:443/ws这种一次到位方便。

**Comment by lxzan** [comment]
CF本来就是个代理
