### ISSUE TITLE
要不整个 discord 讨论群，QQ 基本都不用了

### ISSUE THREAD

**Issue by SpikeWong** [lxzan/gws#22]

**Comment by lxzan** [comment]
telegram吧

**Comment by SpikeWong** [comment]
虽然几次压测下来 gws 比 gorilla 性能好太多，但是选方案的时候还是担心生产上没有经过大规模验证，最后还是选择了 gorilla， 有点遗憾

**Comment by lxzan** [comment]
gorilla也不错，比nhooyr和gobwas强多了

**Comment by lxzan** [comment]
建了个微信群
https://github.com/lxzan/gws/issues/29
