### ISSUE TITLE
Use cases of ReadAsyncGoLimit and ReadAsyncCap configurations

### ISSUE THREAD

**Issue by WeiquanWa** [lxzan/gws#24]
There are two similar configs of `ReadAsyncGoLimit` and `ReadAsyncCap`. What's the differencies between them in terms of use cases?

**Comment by lxzan** [comment]
ReadAsyncGoLimit sets the maximum number of OnMessage calls in parallel on a single connection.
ReadAsyncCap sets the maximum number of messages to be stacked, overflowing will return an error and close the connection.

**Comment by WeiquanWa** [comment]
Thank you for your prompt reply. So `ReadAsyncCap` should be always greater than `ReadAsyncGoLimit`. right?

**Comment by lxzan** [comment]
gws read and write is thread-safe, reads serially, and processes business logic in parallel.

**Comment by WeiquanWa** [comment]
okay. if `ReadAsyncEnabled` is `false`, gws creates two read and write-goroutines of each new connection?

**Comment by WeiquanWa** [comment]
is it possible to read and write messages concurrently using gws?

**Comment by lxzan** [comment]
> okay. if `ReadAsyncEnabled` is `false`, gws creates two read and write-goroutines of each new connection?

No new goroutine will be created, ReadLoop is blocking

**Comment by WeiquanWa** [comment]
to read and write concurrently, we will have to enable `ReadAsyncEnabled`. please confirm

**Comment by lxzan** [comment]
Not required, gws also provides the WriteAsync method, which starts a new goroutine to write the message. 

If you want OnMessage to be processed in parallel, you need to turn it on, or implement your own concurrency control logic.

**Comment by lxzan** [comment]
> is it possible to read and write messages concurrently for single connection using gws?

This possibility exists.

**Comment by WeiquanWa** [comment]
okay cool

Looking at the source code, reader and writer are using a same buffer pool named `myBufferPool` across all connections.  Is it realistic if there are a lot of many concurrent connections and the packet size is large?

**Comment by lxzan** [comment]
How big is it exactly? gws is not optimized for large packets (e.g. writing temporary files), and large packets will block the connection, I think this scenario should use HTTP, WebSocket messages with URLs in them.

**Comment by WeiquanWa** [comment]
I see, seems like the approach to manage memory in gws is a manner to reduce memory usage
