### ISSUE TITLE
关于处理 continue 结束包的疑问

### ISSUE THREAD

**Issue by shaovie** [lxzan/gws#38]
https://github.com/lxzan/gws/blob/master/reader.go#L111C6-L111C6
`	if fin && opcode != OpcodeContinuation {
		return c.emitMessage(&Message{index: index, Opcode: opcode, Data: bytes.NewBuffer(p)}, compressed)
	}`
这里不包含  continue 结束包吗

**Comment by shaovie** [comment]
但是分片消息结束的标志  不就是  fin && opcode != OpcodeContinuation  并且 c.continuationFrame.initialized == true 吗？
你这样提前判断，就会漏掉最后一个分片完成消息的处理了

**Comment by lxzan** [comment]
分片消息结束的标志是 fin && opcode == OpcodeContinuation，分片消息开始的标志是 !fin && opcode == OpcodeText|OpcodeBinary.

**Comment by shaovie** [comment]
哦，我看的文章 写错了
https://zhuanlan.zhihu.com/p/407711596
这里边说的是：
对于最后一个分片的消息, 其 FIN 字段为 1, 并且 Opcode 字段的值为 0x1

我又查了一下，最后一片 opcode=0

**Comment by shaovie** [comment]
TMD  https://zhuanlan.zhihu.com/p/605823149  这个文章 也说的最后一片 opcode=1，妈蛋，要查RFC吗

**Comment by lxzan** [comment]
WS有完善的测试工具：https://lxzan.github.io/gws/reports/servers/

**Comment by lxzan** [comment]
如果只是为了性能压测，你不需要做完整的实现

**Comment by lxzan** [comment]
这么快👍🏻

**Comment by shaovie** [comment]
https://github.com/lxzan/gws/blob/master/protocol.go#L137

给长度赋值，为什么要用 += ?

**Comment by lxzan** [comment]
> https://github.com/lxzan/gws/blob/master/protocol.go#L137
> 
> 给长度赋值，为什么要用 += ?

看RFC帧头结构

**Comment by shaovie** [comment]
我意思是 为什么不是直接 赋值  =  ，为什么要累加

**Comment by lxzan** [comment]
先给赋值 `Payload len` 后设置 `MASK` 也是可以的, 加法不用考虑顺序

```
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
     +-+-+-+-+-------+-+-------------+-------------------------------+
     |F|R|R|R| opcode|M| Payload len |    Extended payload length    |
     |I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
     |N|V|V|V|       |S|             |   (if payload len==126/127)   |
     | |1|2|3|       |K|             |                               |
     +-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
     |     Extended payload length continued, if payload len == 127  |
     + - - - - - - - - - - - - - - - +-------------------------------+
     |                               |Masking-key, if MASK set to 1  |
     +-------------------------------+-------------------------------+
     | Masking-key (continued)       |          Payload Data         |
     +-------------------------------- - - - - - - - - - - - - - - - +
     :                     Payload Data continued ...                :
     + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
     |                     Payload Data continued ...                |
     +---------------------------------------------------------------+
```

**Comment by shaovie** [comment]
> WS有完善的测试工具：https://lxzan.github.io/gws/reports/servers/

这个站为啥打不开？我也翻墙了

**Comment by lxzan** [comment]
> > WS有完善的测试工具：https://lxzan.github.io/gws/reports/servers/
> 
> 这个站为啥打不开？我也翻墙了

检查代理配置 / 换个节点试试

**Comment by shaovie** [comment]
不行，台湾 东京 香港都不行，测试卡在write frame header了，
<img width="451" alt="image" src="https://github.com/lxzan/gws/assets/4576198/cd5c671b-0dc4-481a-b80f-f14cbf18e91e">

测试站 提示invalide frame header

**Comment by shaovie** [comment]
我看测试站，一般都是 上来就先发一个close frame 是吧

**Comment by lxzan** [comment]
> 不行，台湾 东京 香港都不行，测试卡在write frame header了，
> <img width="451" alt="image" src="https://github.com/lxzan/gws/assets/4576198/cd5c671b-0dc4-481a-b80f-f14cbf18e91e">
> 
> 测试站 提示invalide frame header

你的帧头构造得有问题

**Comment by lxzan** [comment]
> 我看测试站，一般都是 上来就先发一个close frame 是吧

断点看

**Comment by shaovie** [comment]
没看出来哪里有问题呢，就两个字节

**Comment by lxzan** [comment]
> 没看出来哪里有问题呢，就两个字节

打印hex字符串，和gws对于，完全一致的话就去网络库找问题

**Comment by shaovie** [comment]
测试流程没问题吧，对方发个close过来，我把close信息原样返回去

**Comment by lxzan** [comment]
> 测试流程没问题吧，对方发个close过来，我把close信息原样返回去

回1000，nil

**Comment by shaovie** [comment]
我有个疑问，为什么switch成功后，对方先发一个  closeframe code=1002 err="WebSocket Protocol” 过来？

**Comment by lxzan** [comment]
> 我有个疑问，为什么switch成功后，对方先发一个  closeframe code=1002 err="WebSocket Protocol” 过来？

协议错误，原因很多，你去gws里面搜一下哪些地方返回了这个

**Comment by shaovie** [comment]
我还有个疑问
https://github.com/lxzan/gws/blob/master/protocol.go#L204

mask 是固定 10:14 吗？不对吧，应该是在payloadlen 后边的4个字节吧

**Comment by lxzan** [comment]
> 我还有个疑问
> https://github.com/lxzan/gws/blob/master/protocol.go#L204
> 
> mask 是固定 10:14 吗？不对吧，应该是在payloadlen 后边的4个字节吧

我只是用这样方式存储，网络传输不是这样的。懒得算偏移量了

**Comment by shaovie** [comment]
这样不会有问题？当payload=uint16的时候 解出来的mask不对吧

**Comment by lxzan** [comment]
> 这样不会有问题？当payload=uint16的时候 解出来的mask不对吧

有问题autobahn早就测出来了

**Comment by shaovie** [comment]
逻辑不通吧

**Comment by shaovie** [comment]
> 我有个疑问，为什么switch成功后，对方先发一个 closeframe code=1002 err="WebSocket Protocol” 过来？

我知道了，应该是我的switch 回应有问题，所以它直接close了

铁子帮我喵一眼，有没有问题，看半天没查出问题

<img width="740" alt="image" src="https://github.com/lxzan/gws/assets/4576198/29c070f7-2ad9-40a5-896f-bcebbba2400f">

**Comment by lxzan** [comment]
> 
> > 我有个疑问，为什么switch成功后，对方先发一个 closeframe code=1002 err="WebSocket Protocol” 过来？
> 
> 我知道了，应该是我的switch 回应有问题，所以它直接close了
> 
> 铁子帮我喵一眼，有没有问题，看半天没查出问题
> 
> <img width="740" alt="image" src="https://github.com/lxzan/gws/assets/4576198/29c070f7-2ad9-40a5-896f-bcebbba2400f">
> 

你的压缩扩展已经写好了？

**Comment by shaovie** [comment]
没啊，还没走到那一步呢，我不返回Extensions 对端也会close 1002

**Comment by lxzan** [comment]
The handshake from the server looks as follows:

        HTTP/1.1 101 Switching Protocols
        Upgrade: websocket
        Connection: Upgrade
        Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=

**Comment by shaovie** [comment]
Sec-WebSocket-Version: 13
这个得有

**Comment by lxzan** [comment]
> Sec-WebSocket-Version: 13
> 这个得有

好好看RFC6455

**Comment by shaovie** [comment]
去掉这个 对端直接报  1002 Invalid reserv

**Comment by lxzan** [comment]
chrome连接gws server:

- request
```
GET ws://127.0.0.1:8000/connect HTTP/1.1
Host: 127.0.0.1:8000
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Upgrade: websocket
Origin: chrome-extension://laookkfknpbbblfpciffpaejjkokdgca
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,pt;q=0.6
Sec-WebSocket-Key: X6zYhq3pAMnwrzBideKXSw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

- response
```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: tp1R6f0smIkI159YZ0+1i92ZIiQ=
```

**Comment by shaovie** [comment]
en，确实不需要，难道是accept 算错了？是抄你的代码啊，哈哈

**Comment by shaovie** [comment]
搞不定了，先放一放

**Comment by shaovie** [comment]
铁子，帮我看看呗 https://github.com/shaovie/goev/blob/main/example/websocket.go

**Comment by shaovie** [comment]
https://gitee.com/casterlee/websocket/blob/master/websocket.go
这个我看了，现在问题就卡在connectHandshake，
connectHandshake 这部分我实在没看出来哪里有问题，为什么测试网站 给我close了

**Comment by lxzan** [comment]
这个地方应该是resp吧, 改完连接就不会自动断开了

<img width="493" alt="image" src="https://github.com/lxzan/gws/assets/17956540/9062503c-f806-4a13-8a70-a179c7781719">

**Comment by shaovie** [comment]
NB，echo我测通过了

**Comment by lxzan** [comment]
通过观察chrome给的信息我怀疑你写入了unexpected contents

**Comment by shaovie** [comment]
除了tcpkali 还有别的工具可以压测吗，我服务器上源码安装tcpkali没成功，编译失败，可能系统太新了，

**Comment by lxzan** [comment]
删掉这行就能编译了
https://github.com/satori-com/tcpkali/blob/3c3175e417366c7ccafba56454903690fede501a/src/tcpkali_syslimits.c#L34

**Comment by shaovie** [comment]
搞定了，给个echo测试的tcpkaili的参数呗

**Comment by shaovie** [comment]
还有问题，tcpkali 有警告
WARNING: Dumb terminal, expect unglorified output.

**Comment by lxzan** [comment]
> 还有问题，tcpkali 有警告 WARNING: Dumb terminal, expect unglorified output.

不崩溃就不用管

**Comment by shaovie** [comment]
WARNING: Dumb terminal, expect unglorified output.
Destination: [127.0.0.1]:8080
Interface lo address [127.0.0.1]:0
Using interface lo to connect to [127.0.0.1]:8080



Could not create 10 connections in allotted time (20s)

**Comment by shaovie** [comment]
http://www.easyswoole.com/wstool.html  这上边测着正常

**Comment by lxzan** [comment]
可能你的网络库还不成熟, 频繁触发OnClose

**Comment by shaovie** [comment]
tcpkali 是按mtu大小发的，所以把frame 分成2个包了 你给的文件是 2396，kali一次只发 1460长度

**Comment by lxzan** [comment]
> tcpkali 是按mtu大小发的，所以把frame 分成2个包了 你给的文件是 2396，kali一次只发 1460长度

异步解析器肯定要考虑半包的

**Comment by shaovie** [comment]
en，有这个逻辑，可能哪里没处理好

**Comment by shaovie** [comment]
好了，铁子，可以对比测测啊，我这只有低配的服务器，不好测

**Comment by lxzan** [comment]
待会我来测一下

**Comment by shaovie** [comment]
看好你哟

**Comment by shaovie** [comment]
> 待会我来测一下

铁子，有结果没

**Comment by lxzan** [comment]
> 铁子，有结果没

昨天发过了. 你后面还有更新吗?

**Comment by shaovie** [comment]
> > 铁子，有结果没
> 
> 昨天发过了. 你后面还有更新吗?

是的  https://github.com/lesismal/chating/issues/2#issuecomment-1671496238

**Comment by lxzan** [comment]
为了公平起见, 所有程序应该使用同样的GOMAXPROCS

**Comment by shaovie** [comment]
> 

是的，我都是设置的 GOMAXPROCS=cpu*2，你也可以把你的P数量调成cpu*2 试试
 但是我的poller 个数可以调，一个 poller 就是一个协程而已

**Comment by shaovie** [comment]
我加的参数是调poller的数量

**Comment by lxzan** [comment]
下行速度代表了goev server, 上行是tcpkali客户端

```
$ tcpkali -c 1000 --connect-rate 5000 -r 500 -T 30s -f ./assets/github.json --ws 127.0.0.1:8080/connect

WARNING: Not reusing TIME_WAIT sockets, might not open 1000 simultaneous connections. Adjust "/proc/sys/net/ipv4/tcp_tw_reuse" value.
Destination: [127.0.0.1]:8080
Interface lo address [127.0.0.1]:0
Using interface lo to connect to [127.0.0.1]:8080
Ramped up to 1000 connections.
Total data sent:     32741.6 MiB (34332043901 bytes)
Total data received: 30164.5 MiB (31629786308 bytes)
Bandwidth per channel: 17.467⇅ Mbps (2183.4 kBps)
Aggregate bandwidth: 8434.355↓, 9154.935↑ Mbps
Packet rate estimate: 860528.4↓, 816585.2↑ (6↓, 2↑ TCP MSS/op)
Test duration: 30.0009 s.
```

**Comment by shaovie** [comment]
好，辛苦

**Comment by shaovie** [comment]
<img width="891" alt="image" src="https://github.com/lxzan/gws/assets/4576198/eb219325-e851-41b1-b95b-0137e6a694a2">
我测着还行啊

**Comment by lxzan** [comment]
我是在linux-arm64 qemu虚拟机里面跑的, 以linux-amd64环境为准

**Comment by shaovie** [comment]
你的测试程序在哪里，我编一个跑跑

**Comment by lxzan** [comment]
> 你的测试程序在哪里，我编一个跑跑

https://github.com/lxzan/gws/blob/master/examples/echo/main.go

**Comment by shaovie** [comment]
铁子，我来啦，有没有别的ws的压测工具啊，tcpkali这种发包方式，对异步解析的太不友好了啊，正式应用谁会每个包都拆开发呢

**Comment by lxzan** [comment]
试试我写的wsbench

**Comment by lxzan** [comment]
你也可以找个小文件，1KB Payload

**Comment by lxzan** [comment]
无穷大

**Comment by shaovie** [comment]
我知道无穷大，它代表啥意思，是协议实现不完整导致没分析到数据吗

**Comment by lxzan** [comment]
> 我知道无穷大，它代表啥意思，是协议实现不完整导致没分析到数据吗

好像是延迟超过10000ms
你试试-c 10000 -n 200

**Comment by shaovie** [comment]
> > 我知道无穷大，它代表啥意思，是协议实现不完整导致没分析到数据吗
> 
> 好像是延迟超过10000ms 你试试-c 10000 -n 200

也是无穷大

**Comment by lxzan** [comment]
> 另外
> https://github.com/lxzan/wsbench/blob/main/internal/random.go
> 
> 这个里边随机不需要再加锁，rand里边已经有锁

你去标准库源码看看注释

**Comment by shaovie** [comment]
> > 另外
> > https://github.com/lxzan/wsbench/blob/main/internal/random.go
> > 这个里边随机不需要再加锁，rand里边已经有锁
> 
> 你去标准库源码看看注释

哦，我的问题，你是自己New了一个 Source

**Comment by shaovie** [comment]
我把payload 字符串部分打印出来了，倒是发的和收到的是一致的
<img width="250" alt="image" src="https://github.com/lxzan/gws/assets/4576198/326c8d6b-eae8-47ce-9180-5ee6e3fa36e8">

**Comment by shaovie** [comment]
<img width="657" alt="image" src="https://github.com/lxzan/gws/assets/4576198/e611ab2f-9622-42ef-9cf8-f62b613f46d4">

换了你的maskxor算法  就说快不快吧，哈哈，

**Comment by lxzan** [comment]
快是很快，感觉延迟不正常

**Comment by shaovie** [comment]
<img width="720" alt="image" src="https://github.com/lxzan/gws/assets/4576198/72053bc2-68fe-452d-a04c-756d6d9b3902">
数据正常了

**Comment by shaovie** [comment]
<img width="716" alt="image" src="https://github.com/lxzan/gws/assets/4576198/f57dad08-b2f5-4c84-a677-2942628056ea">

调一下延时，这数据 NB不NB

**Comment by lxzan** [comment]
NB. 使用了tcp nagle's algorithm没？

**Comment by shaovie** [comment]
> 

用了

**Comment by lxzan** [comment]
> 用了

gws默认是SetNoDelay(true)

**Comment by shaovie** [comment]
en, 一样的

**Comment by shaovie** [comment]
我去吹个NB

**Comment by shaovie** [comment]
<img width="498" alt="image" src="https://github.com/lxzan/gws/assets/4576198/3fe9e869-9a19-4d79-a57d-08d85f5da449">

你的程序我都是 这样编译的，P多点儿好

**Comment by lxzan** [comment]
还是不行. 看起来你搞了fork进程

```
➜  ~ lsof -i :8080
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
___11go_b 2614 caster   15u  IPv4  50588      0t0  TCP *:http-alt (LISTEN)
___11go_b 2614 caster   16u  IPv4  50593      0t0  TCP localhost:http-alt->localhost:38990 (CLOSE_WAIT)
___11go_b 2614 caster   17u  IPv4  50594      0t0  TCP localhost:http-alt->localhost:38994 (CLOSE_WAIT)
___11go_b 2614 caster   18u  IPv4  50595      0t0  TCP localhost:http-alt->localhost:38996 (CLOSE_WAIT)
___11go_b 2614 caster   19u  IPv4  50596      0t0  TCP localhost:http-alt->localhost:39006 (CLOSE_WAIT)
___11go_b 2614 caster   20u  IPv4  50597      0t0  TCP localhost:http-alt->localhost:39012 (CLOSE_WAIT)
___11go_b 2614 caster   21u  IPv4  50598      0t0  TCP localhost:http-alt->localhost:39024 (CLOSE_WAIT)
___11go_b 2614 caster   22u  IPv4  50600      0t0  TCP localhost:http-alt->localhost:39040 (CLOSE_WAIT)
___11go_b 2614 caster   23u  IPv4  50602      0t0  TCP localhost:http-alt->localhost:39054 (CLOSE_WAIT)
```

**Comment by lxzan** [comment]
不是fork进程，一样的pid

**Comment by shaovie** [comment]
刚才提交代码有点儿问题，你现在再pull一下

**Comment by shaovie** [comment]
怎么样，能跑起来了吗

**Comment by lxzan** [comment]
> 怎么样，能跑起来了吗

下午再试试

**Comment by lxzan** [comment]
@shaovie 跑压测内存占用很高

```
┌─────┬─────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name    │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ goev    │ default     │ N/A     │ fork    │ 3391     │ 52s    │ 1    │ online    │ 0%       │ 1.4gb    │ caster   │ disabled │
│ 1   │ gws     │ default     │ N/A     │ fork    │ 3405     │ 52s    │ 1    │ online    │ 0%       │ 87.9mb   │ caster   │ disabled │
└─────┴─────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
```

**Comment by lxzan** [comment]
发送队列里面消息积压太多了?

**Comment by shaovie** [comment]
是的，接收方收的慢，发送方就走异步了，异步就会走队列

**Comment by shaovie** [comment]
你们这个压测，我想应该按排几种实用场景
1. 服务端推流，这个像比特币交易所的行情推送一样，测发包能力
2. 服务端接收，做为下游组件，测试接收能力
3. 如果像wsbench这种 echo，wsbench很可能遇到瓶颈，测试工具很可能收不过来（因为本来read 就比write耗时短)

**Comment by shaovie** [comment]
你们的框架都是同步模式，不会有这种积压的问题，有积压，也会体现在协议栈缓冲区满了，发送方发不出来，不会影响自身的处理

**Comment by shaovie** [comment]
还有个问题，你的框架，如果实现server端定时发ping的话，起个全局的ticker 怎么保证这些packet的顺序呢，框架内好像不提供这个机制吧？
gws不应该只有一个I/O驱动（ReadLoop)的循环，这在实际应用中肯定会有timer事件，怎样保证timer 插入的I/O操作的原子性呢？

**Comment by lxzan** [comment]
> 你们这个压测，我想应该按排几种实用场景
> 1. 服务端推流，这个像比特币交易所的行情推送一样，测发包能力
> 2. 服务端接收，做为下游组件，测试接收能力
> 3. 如果像wsbench这种 echo，wsbench很可能遇到瓶颈，测试工具很可能收不过来（因为本来read 就比write耗时短)

有echo和broadcast两种模式

**Comment by lxzan** [comment]
> 你们的框架都是同步模式，不会有这种积压的问题，有积压，也会体现在协议栈缓冲区满了，发送方发不出来，不会影响自身的处理

gws有异步发送队列，跑benchmark同样可能积压消息

**Comment by lxzan** [comment]
> 还有个问题，你的框架，如果实现server端定时发ping的话，起个全局的ticker 怎么保证这些packet的顺序呢，框架内好像不提供这个机制吧？
> gws不应该只有一个I/O驱动（ReadLoop)的循环，这在实际应用中肯定会有timer事件，怎样保证timer 插入的I/O操作的原子性呢？

你说的原子性指的什么，线程安全？

保证什么顺序？多含多个元素的List才有顺序一说

**Comment by shaovie** [comment]
> 

比如你在ReadLoop中 Write msg1呢，msg1 可能会循环一次才能发完，分成2部分 msg1-part1   msg1-part2
这时候有一个ticker到期了，发送一个Ping Frame，但恰好在msg1-part1之后 part2之前，那这消息顺序是不是就乱了？

**Comment by lxzan** [comment]
> > 
> 读肯定是串行的，但写呢
> 比如你在ReadLoop中 Write msg1呢，msg1 可能会循环一次才能发完，分成2部分 msg1-part1   msg1-part2
> 这时候有一个ticker到期了，发送一个Ping Frame，但恰好在msg1-part1之后 part2之前，那这消息顺序是不是就乱了？

有锁的
