### ISSUE TITLE
OnMessage中的msg没有收回到内存池

### ISSUE THREAD

**Issue by joestarzxh** [lxzan/gws#40]
您好，OnMessage中的msg没有收回到内存池是出于怎么样的考虑呢？

**Comment by lxzan** [comment]
Close之后就会回收. 

gws feature比较多, 不使用固定buffer, msg可以跨协程共享.

**Comment by lxzan** [comment]
那些自动回收msg的ws库, 一般是把固定的buffer和conn绑定, 同步处理请求, 完成处理后reset.

**Comment by joestarzxh** [comment]
看懂了，也就是在OnMessage函数中需要调用msg.close。的确发现很多不同的设计，学习到很多，很棒

**Comment by lxzan** [comment]
> 不在内部调用msg.close，为了减少内存拷贝是吧

主要是出于并发和避免动态扩容方面的考虑

**Comment by joestarzxh** [comment]
明白了

**Comment by lxzan** [comment]
> 的确发现很多不同的设计，学习到很多，很棒

比 `gorilla` 功能更丰富些, 提供了并行处理, 异步写入, 群体广播等特性.
