### ISSUE TITLE
Did you consider prepared messages

### ISSUE THREAD

**Issue by Bios-Marcel** [lxzan/gws#45]
Gorilla/websocket supports prepared messagse. Meaning the frames are generated and compressed once and are then reused. (https://github.com/gorilla/websocket/blob/main/prepared.go#L19)

This is particularly useful if you want to send the same payload to multiple connections. If you are open to this, I could also try implementing it.

**Comment by lxzan** [comment]
Supported. Check out Broadcaster.

**Comment by Bios-Marcel** [comment]
Oh, cool, didn't see. Thanks 🙏
