### ISSUE TITLE
掩码都没处理对

### ISSUE THREAD

**Issue by f4nff** [lxzan/gws#54]
![image](https://github.com/lxzan/gws/assets/19538878/5f6bccc4-6f35-474c-a767-e42db224e89c)

![image](https://github.com/lxzan/gws/assets/19538878/fc761632-46bf-4e24-a303-96d57708a401)

浏览器发了个111,收到一个244

抓包分析出来,显示的原始数据,

**Comment by f4nff** [comment]
国人搞的东西,果然不靠谱.

**Comment by lxzan** [comment]
> 国人搞的东西,果然不靠谱.

那你去用洋人的库吧😄
