### ISSUE TITLE
I'm curious about the Close() method in GWS messaging

### ISSUE THREAD

**Issue by heojeong0141** [lxzan/gws#67]
Do I always need to close the message? It seems different from closing a connection, and I'm not sure about it. Please explain, as it will be used in a chat application.

**Comment by heojeong0141** [comment]
Additionally, I'm curious if it's compatible with external libraries, such as websockets in react-native or flutter.

**Comment by lxzan** [comment]
It should be closed after it has been used. This helps to reduce gc stress and lower memory usage.

**Comment by lxzan** [comment]
> Additionally, I'm curious if it's compatible with external libraries, such as websockets in react-native or flutter.

Compatible. websocket protocol has a unified standard.

**Comment by heojeong0141** [comment]
Thank you for being a great developer, and also for your kind explanations
