### ISSUE TITLE
gin中使用，没有Hijack()接口

### ISSUE THREAD

**Issue by ygcool** [lxzan/gws#69]
运行：![8C $GH0`$LDSXO2X_K@5Y 2](https://github.com/lxzan/gws/assets/16422689/ae95ed7c-7791-43cb-a2be-09424cf0ba7a)

提示：
![JST%199CPT3U6M7R(0AYQQC](https://github.com/lxzan/gws/assets/16422689/a8fd9f5c-dd00-488f-9d75-a0bdfa7db2f8)

**Comment by lxzan** [comment]
不要将TimeoutHandler和WebSocket一起使用

**Comment by ygcool** [comment]
谢谢

**Comment by lxzan** [comment]
> 是不是改了代码不 panic 了，这个问题找了半天。

你加了Recovery ?
