### ISSUE TITLE
能否出篇博客详细介绍下这个框架

### ISSUE THREAD

**Issue by dayueba** [lxzan/gws#7]
比如：与其它ws框架对比，做了哪些优化

**Comment by lxzan** [comment]
周末有时间好好写一篇文章吧.
相比其他基于net/http实现的websocket package, gws
1: 提供websocket event api, 没有增加常驻协程, IOPS更高, 延迟和cpu使用率更低
2. 提供并行读的特性, 可以在单连接上并行处理多个请求
3. 提供非阻塞写的特性, 适合广播场景

**Comment by lxzan** [comment]
看看这个吧
https://segmentfault.com/a/1190000043638040

**Comment by houseme** [comment]
> 看看这个吧 https://segmentfault.com/a/1190000043638040

可以来一个教程。可以 didi 那个 json 库一样，很丝滑的切换 websocket

**Comment by lxzan** [comment]
> 可以来一个教程。可以 didi 那个 json 库一样，很丝滑的切换 websocket
有人帮我写软文就好了 🤣

**Comment by houseme** [comment]
> > 可以来一个教程。可以 didi 那个 json 库一样，很丝滑的切换 websocket
> 
> 有人帮我写软文就好了 🤣

更新一下讨论里的二维码哈  @lxzan 搞个教程吧，后续可以整合到 GoFrame 框架里去哈

**Comment by lxzan** [comment]
行, 下班后写个文章好好介绍下gws在吞吐和内存方面做的努力

**Comment by lxzan** [comment]
还是要靠自己来吹
https://zhuanlan.zhihu.com/p/647114916?

**Comment by lxzan** [comment]
> 更新一下讨论里的二维码哈 @lxzan 搞个教程吧，后续可以整合到 [GoFrame](https://github.com/gogf/gf) 框架里去哈

要帮我在 `goframe` 社区推一下吗? 只要支持 `http.Request` 和 `http.ResponseWriter` 就能无缝接入
