### ISSUE TITLE
Thread safety of methods WriteMessage, WritePing, WritePong, SetDeadline, WriteClose of gws.Conn

### ISSUE THREAD

**Issue by Andrey36652** [lxzan/gws#72]
Hello, I'm considering usage of gws as a websocket client library.
I want to ask: is it safe to call methods WriteMessage, WritePing, WritePong, SetDeadline, WriteClose of same gws.Conn **concurrently** from distinct goroutines?

Example:
```Go
socket, _, err := gws.NewClient(...arguments here...)
go socket.ReadLoop()

go socket.WriteMessage(gws.OpcodeText, []byte("message1"))
go socket.SetDeadline(time.Now().Add(10 * time.Seconds))
go socket.WriteMessage(gws.OpcodeText, []byte("message2"))
go socket.WritePing([]byte("ping"))
go socket.WritePong([]byte("pong"))
```
Or should I wrap with mutex each call of those methods?

**Comment by lxzan** [comment]
![Screenshot_2024-01-16-07-22-21-26_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/lxzan/gws/assets/17956540/53084188-89cc-460a-a452-783709bd25ad)

**Comment by Andrey36652** [comment]
Oh, I thought "Concurrent & Asynchronous Non-Blocking Write" applies only to method WriteAsync.
So, this statement applies to all of the WriteMessage, WritePing, WritePong, SetDeadline, WriteClose methods, right?

**Comment by lxzan** [comment]
yes

**Comment by Andrey36652** [comment]
> net.Conn has an internal lock

Is this implementation platform independent? i.e. same behaviour on Windows, Linux, macos?

**Comment by lxzan** [comment]
It should be consistent, gws does implementations based on the standard network library

**Comment by Andrey36652** [comment]
Thanks

**Comment by Andrey36652** [comment]
Thanks
