### ISSUE TITLE
ClientOption.TlsConfig.ServerName should not contain port number

### ISSUE THREAD

**Issue by Andrey36652** [lxzan/gws#78]
I'm trying to connect to `wss://ws.okx.com:8443/ws/v5/public` as a client and get error `remote error: tls: handshake failure`.
Reason is this line https://github.com/lxzan/gws/blob/5c407ad8e047c7618f321de9b5180caf66002132/client.go#L59  should be
```
option.TlsConfig.ServerName = URL.Hostname()
``` 
because `URL.Host` includes port number, while `URL.Hostname()` does not

**Comment by lxzan** [comment]
Let's manually assign a value to the serverName first, we'll fix that later.

**Comment by lxzan** [comment]
Or use this commit hash for now

```bash
go get -u -v github.com/lxzan/gws@340485a22b22164fcea48ab8cc4e680a6f396100
```

**Comment by nightwolfz** [comment]
Thanks for the fix, I was also having problems with okx

**Comment by lxzan** [comment]
small problem
