### ISSUE TITLE
Chat example - gws: websocket version not supported

### ISSUE THREAD

**Issue by bnbabu55** [lxzan/gws#88]
Hi, I just copied the chat example from the repo and tried to run on port 9090. Then opened the browser with url http://localhost:9090/connect?name=hellokitty&key=123 and I am getting "gws: websocket version not supported" on the browser.

Running this on a Intel based Windows 11 machine, Go 1.22.2 version, if that helps. 

I have not made any changes to the example code except the port number. I checked in Chrome, Firefox, Edge to no avail.

![image](https://github.com/lxzan/gws/assets/56356022/922b146d-4b81-4771-9cf9-ba5e9a9be5ac)

**Comment by lxzan** [comment]
try https://localhost:9090/index.html
