### ISSUE TITLE
chatroom 示例无操作断开

### ISSUE THREAD

**Issue by liuxiaobopro** [lxzan/gws#99]
您好, 我在运行chatroom示例时, 客户端连接之后, 不做任何操作, 一会就断开了, 如图
![image](https://github.com/lxzan/gws/assets/54826000/af7455f5-c283-4153-b1a2-1a0d334dd930)

![image](https://github.com/lxzan/gws/assets/54826000/e9117fca-1cb7-4b97-84de-95bbd614d0c0)

这个超时是需要配置吗? 还是chrome的问题?

**Comment by lxzan** [comment]
把浏览器省电模式关了试试

**Comment by liuxiaobopro** [comment]
这是我开了个chrome分身测试的
![image](https://github.com/lxzan/gws/assets/54826000/066c87c8-665e-4867-aba2-5803be164f67)
然后还是之前的情况, 大约两分钟就断开了

这是我的chrome版本
![image](https://github.com/lxzan/gws/assets/54826000/ee78b7cb-8bce-45e6-ac7c-c3db15c45096)

**Comment by lxzan** [comment]
复现不了, 搞不清你那边是什么情况

**Comment by liuxiaobopro** [comment]
行吧, 我自己换个环境再试试

**Comment by lxzan** [comment]
10min了, 一切正常

![image](https://github.com/lxzan/gws/assets/17956540/0e3f97e0-f428-4b6d-9b12-dc676377a900)
![image](https://github.com/lxzan/gws/assets/17956540/7cfeebc8-0e48-4718-88dd-b1154a7a0d75)

**Comment by liuxiaobopro** [comment]
我发现了这个错误, 我没怎么看明白
![image](https://github.com/lxzan/gws/assets/54826000/a7cb824c-5fc1-48f6-b1c6-cb348a202504)

**Comment by liuxiaobopro** [comment]
![image](https://github.com/lxzan/gws/assets/54826000/a0e702df-59a7-435d-9cea-4a0f089e8097)
